

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dockercompose

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - dockercompose


networks:
  dockercompose: